repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
      - id: remove-crlf
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.2
    hooks:
      - id: search-and-replace
        stages: [commit-msg, commit]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^.*-hook/src/.*/models.py$
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        exclude: ^.*\.aws-sam.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^.*-hook/src/.*/models.py$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ['--verbose']
        verbose: true  # print warnings
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.2.5a9
    hooks:
      - id: cfn-python-lint
        files: ^(?!\..*).*/template\.(json|yml|yaml)$
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.125'
    hooks:
      - id: checkov
        verbose: true
        args: [--soft-fail]