version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "f2f-fe-joe"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-epuw4yrxva44"
s3_prefix = "f2f-fe-joe"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc-cri\" PermissionsBoundary=\"none\""
image_repositories = []
confirm_changeset = true
disable_rollback = true
