module.exports = {
  EEA_ID_CARD: {
    AUSTRIA: { text: "Austria", code: "AUT"},
    BELGIUM: { text: "Belgium", code: "BEL"},
    BULGARIA: { text: "Bulgaria", code: "BGR"},
    CROATIA: { text: "Croatia", code: "HRV"},
    CYPRUS: { text: "Cyprus", code: "CYP"},
    CZECH: { text: "Czech Republic", code: "CZE"},
    ESTONIA: { text: "Estonia", code: "EST"},
    FINLAND: { text: "Finland", code: "FIN"},
    FRANCE: { text: "France", code: "FRA"},
    GERMANY: { text: "Germany", code: "DEU"},
    GREECE: { text: "Greece", code: "GRC"},
    HUNGARY: { text: "Hungary", code: "HUN"},
    IRELAND: { text: "Ireland", code: "IRL"},
    ICELAND: { text: "Iceland", code: "ISL"},
    ITALY: { text: "Italy", code: "ITA"},
    LATVIA: { text: "Latvia", code: "LVA"},
    LIECHTENSTEIN: { text: "Liechtenstein", code: "LIE"},
    LITHUANIA: { text: "Lithuania", code: "LTU"},
    LUXEMBOURG: { text: "Luxembourg", code: "LUX"},
    MALTA: { text: "Malta", code: "MLT"},
    NETHERLANDS: { text: "Netherlands", code: "NLD"},
    NORWAY: { text: "Norway", code: "NOR"},
    POLAND: { text: "Poland", code: "POL"},
    PORTUGAL: { text: "Portugal", code: "PRT"},
    ROMANIA: { text: "Romania", code: "ROU"},
    SLOVAKIA: { text: "Slovakia", code: "SVK"},
    SLOVENIA: { text: "Slovenia", code: "SVN"},
    SPAIN: { text: "Spain", code: "ESP"},
    SWEDEN: { text: "Sweden", code: "SWE"},
  }
}