module.exports = {
  EEA_ID_CARD: {
    AUSTRIA: { text: "Austria", code: "AT"},
    BELGIUM: { text: "Belgium", code: "BE"},
    BULGARIA: { text: "Bulgaria", code: "BG"},
    CROATIA: { text: "Croatia", code: "HR"},
    CYPRUS: { text: "Cyprus", code: "CY"},
    CZECH: { text: "Czech Republic", code: "CZ"},
    ESTONIA: { text: "Estonia", code: "EE"},
    FINLAND: { text: "Finland", code: "FI"},
    FRANCE: { text: "France", code: "FR"},
    GERMANY: { text: "Germany", code: "DE"},
    GREECE: { text: "Greece", code: "GR"},
    HUNGARY: { text: "Hungary", code: "HU"},
    IRELAND: { text: "Ireland", code: "IE"},
    ICELAND: { text: "Iceland", code: "IS"},
    ITALY: { text: "Italy", code: "IT"},
    LATVIA: { text: "Latvia", code: "LV"},
    LIECHTENSTEIN: { text: "Liechtenstein", code: "LI"},
    LITHUANIA: { text: "Lithuania", code: "LT"},
    LUXEMBOURG: { text: "Luxembourg", code: "LU"},
    MALTA: { text: "Malta", code: "MT"},
    NETHERLANDS: { text: "Netherlands", code: "NL"},
    NORWAY: { text: "Norway", code: "NO"},
    POLAND: { text: "Poland", code: "PL"},
    PORTUGAL: { text: "Portugal", code: "PT"},
    ROMANIA: { text: "Romania", code: "RO"},
    SLOVAKIA: { text: "Slovakia", code: "SK"},
    SLOVENIA: { text: "Slovenia", code: "SI"},
    SPAIN: { text: "Spain", code: "ES"},
    SWEDEN: { text: "Sweden", code: "SE"},
  }
}