module.exports = {
  EU_DL_COUNTRIES: {
    AUSTRIA: { text: "Austria", code: "AT", value: "Austria" },
    BELGIUM: { text: "Belgium", code: "BE", value: "Belgium" },
    BULGARIA: { text: "Bulgaria", code: "BG", value: "Bulgaria" },
    CROATIA: { text: "Croatia", code: "HR", value: "Bulgaria" },
    CYPRUS: { text: "Cyprus", code: "CY", value: "Cyprus" },
    CZECH: { text: "Czech Republic", code: "CZ", value: "Czech Republic" },
    DENMARK: { text: "Denmark", code: "DK", value: "Denmark" },
    ESTONIA: { text: "Estonia", code: "EE", value: "Estonia" },
    FINLAND: { text: "Finland", code: "FI", value: "Finland" },
    FRANCE: { text: "France", code: "FR", value: "France" },
    GERMANY: { text: "Germany", code: "DE", value: "Germany" },
    GREECE: { text: "Greece", code: "GR", value: "Greece" },
    HUNGARY: { text: "Hungary", code: "HU", value: "Hungary" },
    ITALY: { text: "Italy", code: "IT", value: "Italy" },
    IRELAND: { text: "Ireland", code: "IE", value: "Ireland"},
    LATVIA: { text: "Latvia", code: "LV", value: "Latvia" },
    LITHUANIA: { text: "Lithuania", code: "LT", value: "Lithuania" },
    LUXEMBOURG: { text: "Luxembourg", code: "LU", value: "Luxembourg" },
    MALTA: { text: "Malta", code: "MT", value: "Malta" },
    NETHERLANDS: { text: "Netherlands", code: "NL", value: "Netherlands" },
    POLAND: { text: "Poland", code: "PL", value: "Poland" },
    PORTUGAL: { text: "Portugal", code: "PT", value: "Portugal" },
    ROMANIA: { text: "Romania", code: "RO", value: "Romania" },
    SLOVAKIA: { text: "Slovakia", code: "SK", value: "Slovakia" },
    SLOVENIA: { text: "Slovenia", code: "SI", value: "Slovenia" },
    SPAIN: { text: "Spain", code: "ES", value: "Spain" },
    SWEDEN: { text: "Sweden", code: "SE", value: "Sweden" },
  }
}