module.exports = {
  EU_DL_COUNTRIES: {
    AUSTRIA: { text: "Austria", code: "AT" },
    BELGIUM: { text: "Belgium", code: "BE" },
    BULGARIA: { text: "Bulgaria", code: "BG" },
    CROATIA: { text: "Croatia", code: "HR"},
    CYPRUS: { text: "Cyprus", code: "CY" },
    CZECH: { text: "Czech Republic", code: "CZ" },
    DENMARK: { text: "Denmark", code: "DK" },
    ESTONIA: { text: "Estonia", code: "EE" },
    FINLAND: { text: "Finland", code: "FI" },
    FRANCE: { text: "France", code: "FR" },
    GERMANY: { text: "Germany", code: "DE" },
    GREECE: { text: "Greece", code: "GR" },
    HUNGARY: { text: "Hungary", code: "HU" },
    ITALY: { text: "Italy", code: "IT" },
    IRELAND: { text: "Ireland", code: "IE"},
    LATVIA: { text: "Latvia", code: "LV" },
    LITHUANIA: { text: "Lithuania", code: "LT" },
    LUXEMBOURG: { text: "Luxembourg", code: "LU" },
    MALTA: { text: "Malta", code: "MT" },
    NETHERLANDS: { text: "Netherlands", code: "NL" },
    POLAND: { text: "Poland", code: "PL" },
    PORTUGAL: { text: "Portugal", code: "PT" },
    ROMANIA: { text: "Romania", code: "RO" },
    SLOVAKIA: { text: "Slovakia", code: "SK" },
    SLOVENIA: { text: "Slovenia", code: "SI" },
    SPAIN: { text: "Spain", code: "ES" },
    SWEDEN: { text: "Sweden", code: "SE" },
  }
}