module.exports = {
  NON_UK_PASSPORT: 
    {
<<<<<<< HEAD
      AFGHANISTAN: { text: "Afghanistan", code: "AF" },
      ALBANIA: { text: "Albania", code: "AL" },
      ALGERIA: { text: "Algeria", code: "DZ" },
      ANDORRA: { text: "Andorra", code: "AD" },
      ANGOLA: { text: "Angola", code: "AO" },
      ANTIGUA: { text: "Antigua and Barbuda", code: "AG" },
      ARGENTINA: { text: "Argentina", code: "AR" },
      ARMENIA: { text: "Armenia", code: "AM" },
      AUSTRALIA: { text: "Australia", code: "AU" },
      AUSTRIA: { text: "Austria", code: "AT" },
      AZERBAIJAN: {	text: "Azerbaijan", code: "AZ" },
      BAHAMAS: { text: "The Bahamas", code: "BS" },
      BAHRAIN: {code: "BH",	text: "Bahrain" },
      BANGLADESH: {code: "BD", text:	"Bangladesh" },
      BARBADOS: {code: "BB", text:	"Barbados" },
      BELARUS: {code: "BY",	text: "Belarus" },
      BELGIUM: { code: "BE", text:	"Belgium" },
      BELIZE: { code: "BZ", text:	"Belize" },
      BENIN: { code: "BJ", text:	"Benin" },
      BHUTAN: {code: "BT", text:	"Bhutan" },
      BOLIVIA: {code: "BO", text: "Bolivia" },
      BOSNIA: { code: "BA", text: "Bosnia and Herzegovina" },
      BOTSWANA: {code: "BW",	text: "Botswana" },
      BRAZIL: {code: "BR", text:	"Brazil" },
      BRUNEI: { code: "BN", text: "Brunei" },
      BULGARIA: { code: "BG", text: "Bulgaria" },
      BURKINA_FASO: { code: "BF", text: "Burkina Faso" },
      BURUNDI: { code: "BI", text: "Burundi" },
      CAMBODIA: { code: "KH", text: "Cambodia" },
      CAMEROON: { code: "CM", text: "Cameroon" },
      CANADA: { code: "CA", text: "Canada" },
      CAPE_VERDE: { code: "CV", text: "Cape Verde" },
      CAR: { code: "CF",	text: "Central African Republic" },
      CHAD: { code: "TD", text: "Chad" },
      CHILE: { code: "CL", text:	"Chile" },
      CHINA: { code: "CN", text: "China" },
      COLOMBIA: { code: "CO", text: "Colombia" },
      COMOROS: { code: "KM", text:	"Comoros" },
      CONGO: { code: "CG", text: "Congo" },
      COSTA_RICA: { code: "CR", text: "Costa Rica" },
      CROATIA: { code: "HR", text:	"Croatia" },
      CUBA: { code: "CU", text: "Cuba" },
      CYPRUS: {code: "CY", text: "Cyprus" },
      CZECH: { code: "CZ", text: "Czech Republic" },
      DRC: {code: "CD", text: "Democratic Republic of the Congo" },
      DENMARK: { code: "DK", text: "Denmark" },
      DJIBOUTI: { code: "DJ", text: "Djibouti" },
      DOMINICA: { code: "DM", text: "Dominica" },
      DOMINICAN_REP: { code: "DO",	text: "Dominican Republic" },
      EAST_TIMOR: { code: "TL", text: "East Timor" },
      ECUADOR: { code: "EC", text: "Ecuador" },
      EGYPT: { code: "EG", text: "Egypt" },
      EL_SALVADOR: { code: "SV", text: "El Salvador" },
      EQ_GUINEA: { code: "GQ", text: "Equatorial Guinea" },
      ERITREA: { code: "ER",	text: "Eritrea" },
      ESTONIA: { code: "EE",	text: "Estonia" },
      ESQATINI: { code: "SZ", text: "Eswatini" },
      ETHIOPIA: { code: "ET", text: "Ethiopia" },
      FIJI: { code: "FJ", text: "Fiji" },
      FINLAND: { code: "FI", text: "Finland" },
      FRANCE: { code: "FR", text: "France" },
      GABON: { code: "GA", text: "Gabon" },
      THE_GAMBIA: { code: "GM", text: "The Gambia" },
      GEORGIA: { code: "GE", text: "Georgia" },
      GERMANY: { code: "DE", text: "Germany" },
      GHANA: { code: "GH", text: "Ghana" },
      GREECE: { code: "GR", text: "Greece" },
      GRENADA: { code: "GD", text: "Grenada" },
      GUATEMALA: { code: "GT", text: "Guatemala" },
      GUINEA: { code: "GN", text: "Guinea" },
      GUINEA_BISSAU: { code: "GW", text: "Guinea-Bissau" },
      GUYANA: { code: "GY", text: "Guyana" },
      HAITI: { code: "HT", text: "Haiti" },
      HONDURAS: { code: "HN", text: "Honduras" },
      HUNGARY: { code: "HU", text: "Hungary" },
      ICELAND: { code: "IS", text: "Iceland" },
      INDIA: { code: "IN", text: "India" },
      INDONESIA: { code: "ID", text: "Indonesia" },
      IRAN: { code: "IR", text: "Iran" },
      IRAQ: { code: "IQ", text: "Iraq" },
      IRELAND: { code: "IE", text: "Ireland" },
      ISRAEL: { code: "IL", text: "Israel" },
      ITALY: { code: "IT", text: "Italy" },
      IVORY_COAST: { code: "CI", text: "Ivory Coast" },
      JAMAICA: { code: "JM", text: "Jamaica" },
      JAPAN: { code: "JP", text: "Japan" },
      JORDAN: { code: "JO", text: "Jordan" },
      KAZAKHSTAN: { code: "KZ", text: "Kazakhstan" },
      KENYA: { code: "KE", text: "Kenya" },
      KIRIBATI: { code: "KI", text: "Kiribati" },
      KOSOVO: { code: "XK", text: "Kosovo" },
      KUWAIT: { code: "KW", text: "Kuwait" },
      KYRGYZSTAN: { code: "KG", text: "Kyrgyzstan" },
      LAOS: { code: "LA", text: "Laos" },
      LATVIA: { code: "LV", text: "Latvia" },
      LEBANON: { code: "LB", text: "Lebanon" },
      LESOTHO: { code: "LS", text: "Lesotho" },
      LIBERIA: { code: "LR", text: "Liberia" },
      LIBYA: { code: "LY", text: "Libya" },
      LIECHTENSTEIN: { code: "LI", text: "Liechtenstein" },
      LITHUANIA: { code: "LT", text: "Lithuania" },
      LUXEMBOURG: { code: "LU", text: "Luxembourg" },
      MADAGASCAR: { code: "MG", text: "Madagascar"},
      MALAWAI: { code: "MW", text: "Malawi" },
      MALAYSIA: { code: "MY", text: "Malaysia" },
      MALDIVES: { code: "MV", text: "Maldives" },
      MALI: { code: "ML", text: "Mali" },
      MALTA: { code: "MT", text: "Malta" },
      MARSHALL_ISLANDS: { code: "MH", text: "Marshall Islands" },
      MAURITANIA: { code: "MR", text: "Mauritania" },
      MAURITIUS: { code: "MU", text: "Mauritius" },
      MEXICO: { code: "MX", text: "Mexico" },
      MICRONESIA: { code: "FM", text: "Micronesia" },
      MOLDOVA: { code: "MD", text: "Moldova" },
      MONACO: { code: "MC", text: "Monaco" },
      MONGOLIA: { code: "MN", text: "Mongolia" },
      MONTENEGRO: { code: "ME", text: 	"Montenegro" },
      MOROCCO: { code: "MA", text: "Morocco" },
      MOZAMBIQUE: { code: "MZ", text: "Mozambique" },
      MYANMAR: { code: "MM", text:	"Myanmar (Burma)" },
      NAMIBIA: { code: "NA", text: "Namibia" },
      NAURU: { code: "NR", text: "Nauru" },
      NEPAL: { code: "NP", text: "Nepal" },
      NETHERLANDS: { code: "NL", text: "Netherlands" },
      NEW_ZEALAND: { code: "NZ", text: "New Zealand" },
      NICARAGUA: { code: "NI", text: "Nicaragua" },
      NIGER: { code: "NE", text: "Niger" },
      NIGERIA: { code: "NG", text: "Nigeria" },
      NORTH_KOREA: { code: "KP", text: "North Korea" },
      N_MACEDONIA: { code: "MK", text: "North Macedonia", },
      NORWAY: { code: "NO", text: "Norway" },
      OMAN: { code: "OM", text: "Oman"},
      PAKISTAN: { code: "PK", text: "Pakistan" },
      PALAU: { code: "PW", text: "Palau" },
      PANAMA: { code: "PA", text: "Panama" },
      PAPUA_NEW_GUINEA: { code: "PG", text: "Papua New Guinea" },
      PARAGUAY: { code: "PY", text: "Paraguay"},
      PERU: { code: "PE", text: "Peru" },
      PHILIPPINES: { code: "PH", text: "Philippines" },
      POLAND: { code: "PL", text: "Poland" },
      PORTUGAL: { code: "PT", text: "Portugal"},
      QATAR: { code: "QA", text: "Qatar" },
      ROMANIA: { code: "RO", text: "Romania" },
      RUSSIA: { code: "RU", text: "Russia" },
      RWANDA: { code: "RW", text: "Rwanda" },
      SAMOA: { code: "WS", text: "Samoa" },
      SAN_MARINO: { code: "SM", text: "San Marino" },
      SAO_TOME: { code: "ST", text: "Sao Tome and Principe" },
      SAUDI_ARABIA: { code: "SA", text: "Saudi Arabia" },
      SENEGAL: { code: "SN", text: "Senegal" },
      SERBIA: { code: "RS", text: "Serbia" },
      SEYCHELLES: { code: "SC", text: "Seychelles" },
      SIERRA_LEONE: { code: "SL", text: "Sierra Leone" },
      SINGAPORE: { code: "SG", text: "Singapore" },
      SLOVAKIA: { code: "SK", text: "Slovakia" },
      SLOVENIA: { code: "SI", text: "Slovenia"},
      SOLOMON_ISLANDS: { code: "SB", text: "Solomon Islands" },
      SOMALIA: { code: "SO", text: "Somalia" },
      SOUTH_AFRICA: { code: "ZA", text: "South Africa" },
      SOUTH_KOREA: { code: "KR", text: "South Korea" },
      SOUTH_SUDAN: { code: "SS", text: "South Sudan" },
      SPAIN: { code: "ES", text: "Spain" },
      SRI_LANKA: { code: "LK", text: "Sri Lanka" },
      ST_KITTS: { code: "KN", text: "St Kitts and Nevis" },
      ST_LUCIA: { code: "LC", text: "St Lucia" },
      ST_VINCENT: { code: "VC", text: "St Vincent" },
      SUDAN: { code: "SD", text: "Sudan" },
      SURINAME: { code: "SR", text: "Suriname" },
      SWEDEN: { code: "SE", text: "Sweden" },
      SWITZERLAND: { code: "CH", text: "Switzerland" },
      SYRIA: { code: "SY", text: "Syria" },
      TAJIKISTAN: { code: "TJ", text: "Tajikistan" },
      TANZANIA: { code: "TZ", text: "Tanzania" },
      THAILAND: { code: "TH", text: "Thailand" },
      TOGO: { code: "TG", text: "Togo" },
      TONGA: { code: "TO", text: "Tonga" },
      TRINIDAD_TOBAGO: { code: "TT", text: "Trinidad and Tobago" },
      TUNISIA: { code: "TN", text: "Tunisia" },
      TURKEY: { code: "TR", text: "Turkey" },
      TURKMENISTAN: { code: "TM", text: "Turkmenistan" },
      TUVALU: { code: "TV", text: "Tuvalu" },
      UGANDA: { code: "UG", text: "Uganda" },
      UKRAINE: { code: "UA", text: "Ukraine" },
      UAE: { code: "AE", text: "United Arab Emirates" },
      US: { code: "US", text: "United States" },
      URUGUAY: { code: "UY", text: "Uruguay" },
      UZBEKISTAN: { code: "UZ", text: "Uzbekistan" },
      VANUATU: { code: "VU", text: "Vanuatu" },
      VENEZUELA: { code: "VE", text: "Venezuela" },
      VIETNAM: { code: "VN", text: "Vietnam" },
      YEMEN: { code: "YE", text: "Yemen" },
      ZAMBIA: { code: "ZM", text: "Zambia" },
      ZIMBABWE: { code: "ZW", text: "Zimbabwe" }
=======
      AFGHANISTAN: { text: "Afghanistan", value: "AF"},
      ALBANIA: { text: "Albania", value: "AL"},
      ALGERIA: { text: "Algeria", value: "DZ"},
      ANDORRA: { text: "Andorra", value: "AD"},
      ANGOLA: { text: "Angola", value: "AO"},
      ANTIGUA: { text: "Antigua and Barbuda", value: "AG"},
      ARGENTINA: { text: "Argentina", value: "AR"},
      ARMENIA: { text: "Armenia", value: "AM"},
      AUSTRALIA: { text: "Australia", value: "AU"},
      AUSTRIA: { text: "Austria", value: "AT"},
      AZERBAIJAN: {	text: "Azerbaijan", value: "AZ" },
      BAHAMAS: { text: "The Bahamas", value: "BS" },
      BAHRAIN: {value: "BH",	text: "Bahrain" },
      BANGLADESH: {value: "BD", text:	"Bangladesh" },
      BARBADOS: {value: "BB", text:	"Barbados" },
      BELARUS: {value: "BY",	text: "Belarus" },
      BELGIUM: { value: "BE", text:	"Belgium"},
      BELIZE: { value: "BZ", text:	"Belize" },
      BENIN: { value: "BJ", text:	"Benin" },
      BHUTAN: {value: "BT", text:	"Bhutan" },
      BOLIVIA: {value: "BO", text: "Bolivia" },
      BOSNIA: { value: "BA", text: "Bosnia and Herzegovina" },
      BOTSWANA: {value: "BW",	text: "Botswana"},
      BRAZIL: {value: "BR", text:	"Brazil"},
      BRUNEI: { value: "BN", text: "Brunei" },
      BULGARIA: { value: "BG", text: "Bulgaria"},
      BURKINA_FASO: { value: "BF", text: "Burkina Faso"},
      BURUNDI: { value: "BI", text: "Burundi"},
      CAMBODIA: { value: "KH", text: "Cambodia"},
      CAMEROON: { value: "CM", text: "Cameroon"},
      CANADA: { value: "CA", text: "Canada"},
      CAPE_VERDE: { value: "CV", text: "Cape Verde"},
      CAR: { value: "CF",	text: "Central African Republic"},
      CHAD: { value: "TD", text: "Chad"},
      CHILE: { value: "CL", text:	"Chile"},
      CHINA: { value: "CN", text: "China"},
      COLOMBIA: { value: "CO", text: "Colombia"},
      COMOROS: { value: "KM", text:	"Comoros"},
      CONGO: { value: "CG", text: "Congo"},
      COSTA_RICA: { value: "CR", text: "Costa Rica"},
      CROATIA: { value: "HR", text:	"Croatia"},
      CUBA: { value: "CU", text: "Cuba"},
      CYPRUS: {value: "CY", text: "Cyprus"},
      CZECH: { value: "CZ", text: "Czech Republic"},
      DRC: {value: "CD", text: "Democratic Republic of the Congo"},
      DENMARK: { value: "DK", text: "Denmark"},
      DJIBOUTI: { value: "DJ", text: "Djibouti"},
      DOMINICA: { value: "DM", text: "Dominica" },
      DOMINICAN_REP: { value: "DO",	text: "Dominican Republic" },
      EAST_TIMOR: { value: "TL", text: "East Timor"},
      ECUADOR: { value: "EC", text: "Ecuador"},
      EGYPT: { value: "EG", text: "Egypt" },
      EL_SALVADOR: { value: "SV", text: "El Salvador" },
      EQ_GUINEA: { value: "GQ", text: "Equatorial Guinea"},
      ERITREA: { value: "ER",	text: "Eritrea"},
      ESTONIA: { value: "EE",	text: "Estonia"},
      ESQATINI: { value: "SZ", text: "Eswatini" },
      ETHIOPIA: { value: "ET", text: "Ethiopia" },
      FIJI: { value: "FJ", text: "Fiji" },
      FINLAND: { value: "FI", text: "Finland" },
      FRANCE: { value: "FR", text: "France" },
      GABON: { value: "GA", text: "Gabon" },
      THE_GAMBIA: { value: "GM", text: "The Gambia" },
      GEORGIA: { value: "GE", text: "Georgia" },
      GERMANY: { value: "DE", text: "Germany" },
      GHANA: { value: "GH", text: "Ghana" },
      GREECE: { value: "GR", text: "Greece" },
      GRENADA: { value: "GD", text: "Grenada" },
      GUATEMALA: { value: "GT", text: "Guatemala" },
      GUINEA: { value: "GN", text: "Guinea" },
      GUINEA_BISSAU: { value: "GW", text: "Guinea-Bissau" },
      GUYANA: { value: "GY", text: "Guyana" },
      HAITI: { value: "HT", text: "Haiti" },
      HONDURAS: { value: "HN", text: "Honduras" },
      HUNGARY: { value: "HU", text: "Hungary" },
      ICELAND: { value: "IS", text: "Iceland" },
      INDIA: { value: "IN", text: "India" },
      INDONESIA: { value: "ID", text: "Indonesia" },
      IRAN: { value: "IR", text: "Iran" },
      IRAQ: { value: "IQ", text: "Iraq" },
      IRELAND: { value: "IE", text: "Ireland" },
      ISRAEL: { value: "IL", text: "Israel" },
      ITALY: { value: "IT", text: "Italy" },
      IVORY_COAST: { value: "CI", text: "Ivory Coast"},
      JAMAICA: { value: "JM", text: "Jamaica" },
      JAPAN: { value: "JP", text: "Japan" },
      JORDAN: { value: "JO", text: "Jordan" },
      KAZAKHSTAN: { value: "KZ", text: "Kazakhstan" },
      KENYA: { value: "KE", text: "Kenya" },
      KIRIBATI: { value: "KI", text: "Kiribati" },
      KOSOVO: { value: "XK", text: "Kosovo" },
      KUWAIT: { value: "KW", text: "Kuwait" },
      KYRGYZSTAN: { value: "KG", text: "Kyrgyzstan" },
      LAOS: { value: "LA", text: "Laos" },
      LATVIA: { value: "LV", text: "Latvia" },
      LEBANON: { value: "LB", text: "Lebanon" },
      LESOTHO: { value: "LS", text: "Lesotho" },
      LIBERIA: { value: "LR", text: "Liberia" },
      LIBYA: { value: "LY", text: "Libya" },
      LIECHTENSTEIN: { value: "LI", text: "Liechtenstein" },
      LITHUANIA: { value: "LT", text: "Lithuania" },
      LUXEMBOURG: { value: "LU", text: "Luxembourg" },
      MADAGASCAR: { value: "MG", text: "Madagascar"},
      MALAWAI: { value: "MW", text: "Malawi" },
      MALAYSIA: { value: "MY", text: "Malaysia" },
      MALDIVES: { value: "MV", text: "Maldives" },
      MALI: { value: "ML", text: "Mali" },
      MALTA: { value: "MT", text: "Malta" },
      MARSHALL_ISLANDS: { value: "MH", text: "Marshall Islands" },
      MAURITANIA: { value: "MR", text: "Mauritania" },
      MAURITIUS: { value: "MU", text: "Mauritius" },
      MEXICO: { value: "MX", text: "Mexico" },
      MICRONESIA: { value: "FM", text: "Micronesia" },
      MOLDOVA: { value: "MD", text: "Moldova" },
      MONACO: { value: "MC", text: "Monaco" },
      MONGOLIA: { value: "MN", text: "Mongolia" },
      MONTENEGRO: { value: "ME", text: 	"Montenegro" },
      MOROCCO: { value: "MA", text: "Morocco" },
      MOZAMBIQUE: { value: "MZ", text: "Mozambique" },
      MYANMAR: { value: "MM", text:	"Myanmar (Burma)" },
      NAMIBIA: { value: "NA", text: "Namibia" },
      NAURU: { value: "NR", text: "Nauru" },
      NEPAL: { value: "NP", text: "Nepal" },
      NETHERLANDS: { value: "NL", text: "Netherlands" },
      NEW_ZEALAND: { value: "NZ", text: "New Zealand" },
      NICARAGUA: { value: "NI", text: "Nicaragua" },
      NIGER: { value: "NE", text: "Niger" },
      NIGERIA: { value: "NG", text: "Nigeria" },
      NORTH_KOREA: { value: "KP", text: "North Korea" },
      N_MACEDONIA: { value: "MK", text: "North Macedonia", },
      NORWAY: { value: "NO", text: "Norway" },
      OMAN: { value: "OM", text: "Oman"},
      PAKISTAN: { value: "PK", text: "Pakistan" },
      PALAU: { value: "PW", text: "Palau" },
      PANAMA: { value: "PA", text: "Panama" },
      PAPUA_NEW_GUINEA: { value: "PG", text: "Papua New Guinea" },
      PARAGUAY: { value: "PY", text: "Paraguay"},
      PERU: { value: "PE", text: "Peru" },
      PHILIPPINES: { value: "PH", text: "Philippines" },
      POLAND: { value: "PL", text: "Poland" },
      PORTUGAL: { value: "PT", text: "Portugal"},
      QATAR: { value: "QA", text: "Qatar" },
      ROMANIA: { value: "RO", text: "Romania" },
      RUSSIA: { value: "RU", text: "Russia" },
      RWANDA: { value: "RW", text: "Rwanda" },
      SAMOA: { value: "WS", text: "Samoa" },
      SAN_MARINO: { value: "SM", text: "San Marino" },
      SAO_TOME: { value: "ST", text: "Sao Tome and Principe" },
      SAUDI_ARABIA: { value: "SA", text: "Saudi Arabia" },
      SENEGAL: { value: "SN", text: "Senegal" },
      SERBIA: { value: "RS", text: "Serbia" },
      SEYCHELLES: { value: "SC", text: "Seychelles" },
      SIERRA_LEONE: { value: "SL", text: "Sierra Leone" },
      SINGAPORE: { value: "SG", text: "Singapore" },
      SLOVAKIA: { value: "SK", text: "Slovakia" },
      SLOVENIA: { value: "SI", text: "Slovenia"},
      SOLOMON_ISLANDS: { value: "SB", text: "Solomon Islands" },
      SOMALIA: { value: "SO", text: "Somalia" },
      SOUTH_AFRICA: { value: "ZA", text: "South Africa" },
      SOUTH_KOREA: { value: "KR", text: "South Korea" },
      SOUTH_SUDAN: { value: "SS", text: "South Sudan" },
      SPAIN: { value: "ES", text: "Spain" },
      SRI_LANKA: { value: "LK", text: "Sri Lanka" },
      ST_KITTS: { value: "KN", text: "St Kitts and Nevis" },
      ST_LUCIA: { value: "LC", text: "St Lucia" },
      ST_VINCENT: { value: "VC", text: "St Vincent" },
      SUDAN: { value: "SD", text: "Sudan" },
      SURINAME: { value: "SR", text: "Suriname" },
      SWEDEN: { value: "SE", text: "Sweden" },
      SWITZERLAND: { value: "CH", text: "Switzerland" },
      SYRIA: { value: "SY", text: "Syria" },
      TAJIKISTAN: { value: "TJ", text: "Tajikistan" },
      TANZANIA: { value: "TZ", text: "Tanzania" },
      THAILAND: { value: "TH", text: "Thailand" },
      TOGO: { value: "TG", text: "Togo" },
      TONGA: { value: "TO", text: "Tonga" },
      TRINIDAD_TOBAGO: { value: "TT", text: "Trinidad and Tobago" },
      TUNISIA: { value: "TN", text: "Tunisia" },
      TURKEY: { value: "TR", text: "Turkey" },
      TURKMENISTAN: { value: "TM", text: "Turkmenistan" },
      TUVALU: { value: "TV", text: "Tuvalu" },
      UGANDA: { value: "UG", text: "Uganda" },
      UKRAINE: { value: "UA", text: "Ukraine" },
      UAE: { value: "AE", text: "United Arab Emirates" },
      US: { value: "US", text: "United States" },
      URUGUAY: { value: "UY", text: "Uruguay" },
      UZBEKISTAN: { value: "UZ", text: "Uzbekistan" },
      VANUATU: { value: "VU", text: "Vanuatu" },
      VENEZUELA: { value: "VE", text: "Venezuela" },
      VIETNAM: { value: "VN", text: "Vietnam" },
      YEMEN: { value: "YE", text: "Yemen" },
      ZAMBIA: { value: "ZM", text: "Zambia" },
      ZIMBABWE: { value: "ZW", text: "Zimbabwe" }
>>>>>>> origin/main
    }
}