module.exports = {
  NON_UK_PASSPORT: 
    {
      AFGHANISTAN: { text: "Afghanistan", value: "AFG"},
      ALBANIA: { text: "Albania", value: "ALB"},
      ALGERIA: { text: "Algeria", value: "DZA"},
      ANDORRA: { text: "Andorra", value: "AND"},
      ANGOLA: { text: "Angola", value: "AGO"},
      ANTIGUA: { text: "Antigua and Barbuda", value: "ATG"},
      ARGENTINA: { text: "Argentina", value: "ARG"},
      ARMENIA: { text: "Armenia", value: "ARM"},
      AUSTRALIA: { text: "Australia", value: "AUS"},
      AUSTRIA: { text: "Austria", value: "AUT"},
      AZERBAIJAN: {	text: "Azerbaijan", value: "AZE" },
      BAHAMAS: { text: "The Bahamas", value: "BHS" },
      BAHRAIN: {value: "BHR",	text: "Bahrain" },
      BANGLADESH: {value: "BGD", text:	"Bangladesh" },
      BARBADOS: {value: "BRB", text:	"Barbados" },
      BELARUS: {value: "BLR",	text: "Belarus" },
      BELGIUM: { value: "BEL", text:	"Belgium"},
      BELIZE: { value: "BLZ", text:	"Belize" },
      BENIN: { value: "BEN", text:	"Benin" },
      BHUTAN: {value: "BTN", text:	"Bhutan" },
      BOLIVIA: {value: "BOL", text: "Bolivia" },
      BOSNIA: { value: "BIH", text: "Bosnia and Herzegovina" },
      BOTSWANA: {value: "BWA",	text: "Botswana"},
      BRAZIL: {value: "BRA", text:	"Brazil"},
      BRUNEI: { value: "BRN", text: "Brunei" },
      BULGARIA: { value: "BGR", text: "Bulgaria"},
      BURKINA_FASO: { value: "BFA", text: "Burkina Faso"},
      BURUNDI: { value: "BDI", text: "Burundi"},
      CAMBODIA: { value: "KHM", text: "Cambodia"},
      CAMEROON: { value: "CMR", text: "Cameroon"},
      CANADA: { value: "CAN", text: "Canada"},
      CAPE_VERDE: { value: "CPV", text: "Cape Verde"},
      CAR: { value: "CAF",	text: "Central African Republic"},
      CHAD: { value: "TCD", text: "Chad"},
      CHILE: { value: "CHL", text:	"Chile"},
      CHINA: { value: "CHN", text: "China"},
      COLOMBIA: { value: "COL", text: "Colombia"},
      COMOROS: { value: "COM", text:	"Comoros"},
      CONGO: { value: "COG", text: "Congo"},
      COSTA_RICA: { value: "CRI", text: "Costa Rica"},
      CROATIA: { value: "HRV", text:	"Croatia"},
      CUBA: { value: "CUB", text: "Cuba"},
      CYPRUS: {value: "CYP", text: "Cyprus"},
      CZECH: { value: "CZE", text: "Czech Republic"},
      DRC: {value: "COD", text: "Democratic Republic of the Congo"},
      DENMARK: { value: "DNK", text: "Denmark"},
      DJIBOUTI: { value: "DJI", text: "Djibouti"},
      DOMINICA: { value: "DMA", text: "Dominica" },
      DOMINICAN_REP: { value: "DOM",	text: "Dominican Republic" },
      EAST_TIMOR: { value: "TLS", text: "East Timor"},
      ECUADOR: { value: "ECU", text: "Ecuador"},
      EGYPT: { value: "EGY", text: "Egypt" },
      EL_SALVADOR: { value: "SLV", text: "El Salvador" },
      EQ_GUINEA: { value: "GNQ", text: "Equatorial Guinea"},
      ERITREA: { value: "ERI",	text: "Eritrea"},
      ESTONIA: { value: "EST",	text: "Estonia"},
      ESQATINI: { value: "SWZ", text: "Eswatini" },
      ETHIOPIA: { value: "ETH", text: "Ethiopia" },
      FIJI: { value: "FJI", text: "Fiji" },
      FINLAND: { value: "FIN", text: "Finland" },
      FRANCE: { value: "FRA", text: "France" },
      GABON: { value: "GAB", text: "Gabon" },
      THE_GAMBIA: { value: "GMB", text: "The Gambia" },
      GEORGIA: { value: "GEO", text: "Georgia" },
      GERMANY: { value: "DEU", text: "Germany" },
      GHANA: { value: "GHA", text: "Ghana" },
      GREECE: { value: "GRC", text: "Greece" },
      GRENADA: { value: "GRD", text: "Grenada" },
      GUATEMALA: { value: "GTM", text: "Guatemala" },
      GUINEA: { value: "GIN", text: "Guinea" },
      GUINEA_BISSAU: { value: "GNB", text: "Guinea-Bissau" },
      GUYANA: { value: "GUY", text: "Guyana" },
      HAITI: { value: "HTI", text: "Haiti" },
      HONDURAS: { value: "HND", text: "Honduras" },
      HUNGARY: { value: "HUN", text: "Hungary" },
      ICELAND: { value: "ISL", text: "Iceland" },
      INDIA: { value: "IND", text: "India" },
      INDONESIA: { value: "IDN", text: "Indonesia" },
      IRAN: { value: "IRN", text: "Iran" },
      IRAQ: { value: "IRQ", text: "Iraq" },
      IRELAND: { value: "IRL", text: "Ireland" },
      ISRAEL: { value: "ISR", text: "Israel" },
      ITALY: { value: "ITA", text: "Italy" },
      IVORY_COAST: { value: "CIV", text: "Ivory Coast"},
      JAMAICA: { value: "JAM", text: "Jamaica" },
      JAPAN: { value: "JPN", text: "Japan" },
      JORDAN: { value: "JOR", text: "Jordan" },
      KAZAKHSTAN: { value: "KAZ", text: "Kazakhstan" },
      KENYA: { value: "KEN", text: "Kenya" },
      KIRIBATI: { value: "KIR", text: "Kiribati" },
      KOSOVO: { value: "XXK", text: "Kosovo" },
      KUWAIT: { value: "KWT", text: "Kuwait" },
      KYRGYZSTAN: { value: "KGZ", text: "Kyrgyzstan" },
      LAOS: { value: "LAO", text: "Laos" },
      LATVIA: { value: "LVA", text: "Latvia" },
      LEBANON: { value: "LBN", text: "Lebanon" },
      LESOTHO: { value: "LSO", text: "Lesotho" },
      LIBERIA: { value: "LBR", text: "Liberia" },
      LIBYA: { value: "LBY", text: "Libya" },
      LIECHTENSTEIN: { value: "LIE", text: "Liechtenstein" },
      LITHUANIA: { value: "LTU", text: "Lithuania" },
      LUXEMBOURG: { value: "LUX", text: "Luxembourg" },
      MADAGASCAR: { value: "MDG", text: "Madagascar"},
      MALAWAI: { value: "MWI", text: "Malawi" },
      MALAYSIA: { value: "MYS", text: "Malaysia" },
      MALDIVES: { value: "MDV", text: "Maldives" },
      MALI: { value: "MLI", text: "Mali" },
      MALTA: { value: "MLT", text: "Malta" },
      MARSHALL_ISLANDS: { value: "MHL", text: "Marshall Islands" },
      MAURITANIA: { value: "MRT", text: "Mauritania" },
      MAURITIUS: { value: "MUS", text: "Mauritius" },
      MEXICO: { value: "MEX", text: "Mexico" },
      MICRONESIA: { value: "FSM", text: "Micronesia" },
      MOLDOVA: { value: "MDA", text: "Moldova" },
      MONACO: { value: "MCO", text: "Monaco" },
      MONGOLIA: { value: "MNG", text: "Mongolia" },
      MONTENEGRO: { value: "MNE", text: 	"Montenegro" },
      MOROCCO: { value: "MAR", text: "Morocco" },
      MOZAMBIQUE: { value: "MOZ", text: "Mozambique" },
      MYANMAR: { value: "MMR", text:	"Myanmar (Burma)" },
      NAMIBIA: { value: "NAM", text: "Namibia" },
      NAURU: { value: "NRU", text: "Nauru" },
      NEPAL: { value: "NPL", text: "Nepal" },
      NETHERLANDS: { value: "NLD", text: "Netherlands" },
      NEW_ZEALAND: { value: "NZL", text: "New Zealand" },
      NICARAGUA: { value: "NIC", text: "Nicaragua" },
      NIGER: { value: "NER", text: "Niger" },
      NIGERIA: { value: "NGA", text: "Nigeria" },
      NORTH_KOREA: { value: "PRK", text: "North Korea" },
      N_MACEDONIA: { value: "MKD", text: "North Macedonia", },
      NORWAY: { value: "NOR", text: "Norway" },
      OMAN: { value: "OMN", text: "Oman"},
      PAKISTAN: { value: "PAK", text: "Pakistan" },
      PALAU: { value: "PLW", text: "Palau" },
      PANAMA: { value: "PAN", text: "Panama" },
      PAPUA_NEW_GUINEA: { value: "PNG", text: "Papua New Guinea" },
      PARAGUAY: { value: "PRY", text: "Paraguay"},
      PERU: { value: "PER", text: "Peru" },
      PHILIPPINES: { value: "PHL", text: "Philippines" },
      POLAND: { value: "POL", text: "Poland" },
      PORTUGAL: { value: "PRT", text: "Portugal"},
      QATAR: { value: "QA", text: "Qatar" },
      ROMANIA: { value: "RO", text: "Romania" },
      RUSSIA: { value: "RU", text: "Russia" },
      RWANDA: { value: "RW", text: "Rwanda" },
      SAMOA: { value: "WS", text: "Samoa" },
      SAN_MARINO: { value: "SM", text: "San Marino" },
      SAO_TOME: { value: "ST", text: "Sao Tome and Principe" },
      SAUDI_ARABIA: { value: "SA", text: "Saudi Arabia" },
      SENEGAL: { value: "SN", text: "Senegal" },
      SERBIA: { value: "RS", text: "Serbia" },
      SEYCHELLES: { value: "SC", text: "Seychelles" },
      SIERRA_LEONE: { value: "SL", text: "Sierra Leone" },
      SINGAPORE: { value: "SG", text: "Singapore" },
      SLOVAKIA: { value: "SK", text: "Slovakia" },
      SLOVENIA: { value: "SI", text: "Slovenia"},
      SOLOMON_ISLANDS: { value: "SB", text: "Solomon Islands" },
      SOMALIA: { value: "SO", text: "Somalia" },
      SOUTH_AFRICA: { value: "ZA", text: "South Africa" },
      SOUTH_KOREA: { value: "KR", text: "South Korea" },
      SOUTH_SUDAN: { value: "SS", text: "South Sudan" },
      SPAIN: { value: "ES", text: "Spain" },
      SRI_LANKA: { value: "LK", text: "Sri Lanka" },
      ST_KITTS: { value: "KN", text: "St Kitts and Nevis" },
      ST_LUCIA: { value: "LC", text: "St Lucia" },
      ST_VINCENT: { value: "VC", text: "St Vincent" },
      SUDAN: { value: "SD", text: "Sudan" },
      SURINAME: { value: "SR", text: "Suriname" },
      SWEDEN: { value: "SE", text: "Sweden" },
      SWITZERLAND: { value: "CH", text: "Switzerland" },
      SYRIA: { value: "SY", text: "Syria" },
      TAJIKISTAN: { value: "TJ", text: "Tajikistan" },
      TANZANIA: { value: "TZ", text: "Tanzania" },
      THAILAND: { value: "TH", text: "Thailand" },
      TOGO: { value: "TG", text: "Togo" },
      TONGA: { value: "TO", text: "Tonga" },
      TRINIDAD_TOBAGO: { value: "TT", text: "Trinidad and Tobago" },
      TUNISIA: { value: "TN", text: "Tunisia" },
      TURKEY: { value: "TR", text: "Turkey" },
      TURKMENISTAN: { value: "TM", text: "Turkmenistan" },
      TUVALU: { value: "TV", text: "Tuvalu" },
      UGANDA: { value: "UG", text: "Uganda" },
      UKRAINE: { value: "UA", text: "Ukraine" },
      UAE: { value: "AE", text: "United Arab Emirates" },
      US: { value: "US", text: "United States" },
      URUGUAY: { value: "UY", text: "Uruguay" },
      UZBEKISTAN: { value: "UZ", text: "Uzbekistan" },
      VANUATU: { value: "VU", text: "Vanuatu" },
      VENEZUELA: { value: "VE", text: "Venezuela" },
      VIETNAM: { value: "VN", text: "Vietnam" },
      YEMEN: { value: "YE", text: "Yemen" },
      ZAMBIA: { value: "ZM", text: "Zambia" },
      ZIMBABWE: { value: "ZW", text: "Zimbabwe" }
    }
}