module.exports = {
  NON_UK_PASSPORT: {
    AFGHANISTAN: { text: "Afghanistan", value: "AF"},
    ALBANIA: { text: "Albania", value: "AL"},
    ALGERIA: { text: "Algeria", value: "DZ"},
    ANDORRA: { text: "Andorra", value: "AD"},
    ANGOLA: { text: "Angola", value: "AO"},
    ANTIGUA: { text: "Antigua and Barbuda", value: "AG"},
    ARGENTINA: { text: "Argentina", value: "AR"},
    ARMENIA: { text: "Armenia", value: "AM"},
    AUSTRALIA: { text: "Australia", value: "AU"},
    AUSTRIA: { text: "Austria", value: "AT"},
    AZERBAIJAN: {	text: "Azerbaijan", value: "AZ" },
    BAHAMAS: { text: "The Bahamas", value: "BS" },
    BAHRAIN: {value: "BH",	text: "Bahrain" },
    BANGLADESH: {value: "BD", text:	"Bangladesh" },
    BARBADOS: {value: "BB", text:	"Barbados" },
    BELARUS: {value: "BY",	text: "Belarus" },
    BELGIUM: { value: "BE", text:	"Belgium"},
    BELIZE: { value: "BZ", text:	"Belize" },
    BENIN: { value: "BJ", text:	"Benin" },
    BHUTAN: {value: "BT", text:	"Bhutan" },
    BOLIVIA: {value: "BO", text: "Bolivia" },
    BOSNIA: { value: "BA", text: "Bosnia and Herzegovina" },
    BOTSWANA: {value: "BW",	text: "Botswana"},
    BRAZIL: {value: "BR", text:	"Brazil"},
    BRUNEI: { value: "BN", text: "Brunei" },
    BULGARIA: { value: "BG", text: "Bulgaria"},
    BURKINA_FASO: { value: "BF", text: "Burkina Faso"},
    BURUNDI: { value: "BI", text: "Burundi"},
    CAMBODIA: { value: "KH", text: "Cambodia"},
    CAMEROON: { value: "CM", text: "Cameroon"},
    CANADA: { value: "CA", text: "Canada"},
    CAPE_VERDE: { value: "CV", text: "Cape Verde"},
    CAR: { value: "CF",	text: "Central African Republic"},
    CHAD: { value: "TD", text: "Chad"},
    CHILE: { value: "CL", text:	"Chile"},
    CHINA: { value: "CN", text: "China"},
    COLOMBIA: { value: "CO", text: "Colombia"},
    COMOROS: { value: "KM", text:	"Comoros"},
    CONGO: { value: "CG", text: "Congo"},
    COSTA_RICA: { value: "CR", text: "Costa Rica"},
    CROATIA: { value: "HR", text:	"Croatia"},
    CUBA: { value: "CU", text: "Cuba"},
    CYPRUS: {value: "CY", text: "Cyprus"},
    CZECH: { value: "CZ", text: "Czech Republic"},
    DRC: {value: "CD", text: "Democratic Republic of the Congo"},
    DENMARK: { value: "DK", text: "Denmark"},
    DJIBOUTI: { value: "DJ", text: "Djibouti"},
    DOMINICA: { value: "DM", text: "Dominica" },
    DOMINICAN_REP: { value: "DO",	text: "Dominican Republic" },
    EAST_TIMOR: { value: "TL", text: "East Timor"},
    ECUADOR: { value: "EC", text: "Ecuador"},
    EGYPT: { value: "EG", text: "Egypt" },
    EL_SALVADOR: { value: "SV", text: "El Salvador" },
    EQ_GUINEA: { value: "GQ", text: "Equatorial Guinea"},
    ERITREA: { value: "ER",	text: "Eritrea"},
    ESTONIA: { value: "EE",	text: "Estonia"},
    ESQATINI: { value: "SZ", text: "Eswatini" },
    ETHIOPIA: { value: "ET", text: "Ethiopia" },
    FIJI: { value: "FJ", text: "Fiji" },
    FINLAND: { value: "FI", text: "Finland" },
    FRANCE: { value: "FR", text: "France" },
    GABON: { value: "GA", text: "Gabon" },
    THE_GAMBIA: { value: "GM", text: "The Gambia" },
    GEORGIA: { value: "GE", text: "Georgia" },
    GERMANY: { value: "DE", text: "Germany" },
    GHANA: { value: "GH", text: "Ghana" },
    GREECE: { value: "GR", text: "Greece" },
    GRENADA: { value: "GD", text: "Grenada" },
    GUATEMALA: { value: "GT", text: "Guatemala" },
    GUINEA: { value: "GN", text: "Guinea" },
    GUINEA_BISSAU: { value: "GW", text: "Guinea-Bissau" },
    GUYANA: { value: "GY", text: "Guyana" },
    HAITI: { value: "HT", text: "Haiti" },
    HONDURAS: { value: "HN", text: "Honduras" },
    HUNGARY: { value: "HU", text: "Hungary" },
    ICELAND: { value: "IS", text: "Iceland" },
    INDIA: { value: "IN", text: "India" },
    INDONESIA: { value: "ID", text: "Indonesia" },
    IRAN: { value: "IR", text: "Iran" },
    IRAQ: { value: "IQ", text: "Iraq" },
    IRELAND: { value: "IE", text: "Ireland" },
    ISRAEL: { value: "IL", text: "Israel" },
    ITALY: { value: "IT", text: "Italy" },
    IVORY_COAST: { value: "CI", text: "Ivory Coast"},
    JAMAICA: { value: "JM", text: "Jamaica" },
    JAPAN: { value: "JP", text: "Japan" },
    JORDAN: { value: "JO", text: "Jordan" },
    KAZAKHSTAN: { value: "KZ", text: "Kazakhstan" },
    KENYA: { value: "KE", text: "Kenya" },
    KIRIBATI: { value: "KI", text: "Kiribati" },
    KOSOVO: { value: "XK", text: "Kosovo" },
    KUWAIT: { value: "KW", text: "Kuwait" },
    KYRGYZSTAN: { value: "KG", text: "Kyrgyzstan" },
    LAOS: { value: "LA", text: "Laos" },
    LATVIA: { value: "LV", text: "Latvia" },
    LEBANON: { value: "LB", text: "Lebanon" },
    LESOTHO: { value: "LS", text: "Lesotho" },
    LIBERIA: { value: "LR", text: "Liberia" },
    LIBYA: { value: "LY", text: "Libya" },
    LIECHTENSTEIN: { value: "LI", text: "Liechtenstein" },
    LITHUANIA: { value: "LT", text: "Lithuania" },
    LUXEMBOURG: { value: "LU", text: "Luxembourg" },
    MADAGASCAR: { value: "MG", text: "Madagascar"},
    MALAWAI: { value: "MW", text: "Malawi" },
    MALAYSIA: { value: "MY", text: "Malaysia" },
    MALDIVES: { value: "MV", text: "Maldives" },
    MALI: { value: "ML", text: "Mali" },
    MALTA: { value: "MT", text: "Malta" },
    MARSHALL_ISLANDS: { value: "MH", text: "Marshall Islands" },
    MAURITANIA: { value: "MR", text: "Mauritania" },
    MAURITIUS: { value: "MU", text: "Mauritius" },
    MEXICO: { value: "MX", text: "Mexico" },
    MICRONESIA: { value: "FM", text: "Micronesia" },
    MOLDOVA: { value: "MD", text: "Moldova" },
    MONACO: { value: "MC", text: "Monaco" },
    MONGOLIA: { value: "MN", text: "Mongolia" },
    MONTENEGRO: { value: "ME", text: 	"Montenegro" },
    MOROCCO: { value: "MA", text: "Morocco" },
    MOZAMBIQUE: { value: "MZ", text: "Mozambique" },
    MYANMAR: { value: "MM", text:	"Myanmar (Burma)" },
    NAMIBIA: { value: "NA", text: "Namibia" },
    NAURU: { value: "NR", text: "Nauru" },
    NEPAL: { value: "NP", text: "Nepal" },
    NETHERLANDS: { value: "NL", text: "Netherlands" },
    NEW_ZEALAND: { value: "NZ", text: "New Zealand" },
    NICARAGUA: { value: "NI", text: "Nicaragua" },
    NIGER: { value: "NE", text: "Niger" },
    NIGERIA: { value: "NG", text: "Nigeria" },
    NORTH_KOREA: { value: "KP", text: "North Korea" },
    N_MACEDONIA: { value: "MK", text: "North Macedonia", },
    NORWAY: { value: "NO", text: "Norway" },
    OMAN: { value: "OM", text: "Oman"},
    PAKISTAN: { value: "PK", text: "Pakistan" },
    PALAU: { value: "PW", text: "Palau" },
    PANAMA: { value: "PA", text: "Panama" },
    PAPUA_NEW_GUINEA: { value: "PG", text: "Papua New Guinea" },
    PARAGUAY: { value: "PY", text: "Paraguay"},
    PERU: { value: "PE", text: "Peru" },
    PHILIPPINES: { value: "PH", text: "Philippines" },
    POLAND: { value: "PL", text: "Poland" },
    PORTUGAL: { value: "PT", text: "Portugal"},
    QATAR: { value: "QA", text: "Qatar" },
    ROMANIA: { value: "RO", text: "Romania" },
    RUSSIA: { value: "RU", text: "Russia" },
    RWANDA: { value: "RW", text: "Rwanda" },
    SAMOA: { value: "WS", text: "Samoa" },
    SAN_MARINO: { value: "SM", text: "San Marino" },
    SAO_TOME: { value: "ST", text: "Sao Tome and Principe" },
    SAUDI_ARABIA: { value: "SA", text: "Saudi Arabia" },
    SENEGAL: { value: "SN", text: "Senegal" },
    SERBIA: { value: "RS", text: "Serbia" },
    SEYCHELLES: { value: "SC", text: "Seychelles" },
    SIERRA_LEONE: { value: "SL", text: "Sierra Leone" },
    SINGAPORE: { value: "SG", text: "Singapore" },
    SLOVAKIA: { value: "SK", text: "Slovakia" },
    SLOVENIA: { value: "SI", text: "Slovenia"},
    SOLOMON_ISLANDS: { value: "SB", text: "Solomon Islands" },
    SOMALIA: { value: "SO", text: "Somalia" },
    SOUTH_AFRICA: { value: "ZA", text: "South Africa" },
    SOUTH_KOREA: { value: "KR", text: "South Korea" },
    SOUTH_SUDAN: { value: "SS", text: "South Sudan" },
    SPAIN: { value: "ES", text: "Spain" },
    SRI_LANKA: { value: "LK", text: "Sri Lanka" },
    ST_KITTS: { value: "KN", text: "St Kitts and Nevis" },
    ST_LUCIA: { value: "LC", text: "St Lucia" },
    ST_VINCENT: { value: "VC", text: "St Vincent" },
    SUDAN: { value: "SD", text: "Sudan" },
    SURINAME: { value: "SR", text: "Suriname" },
    SWEDEN: { value: "SE", text: "Sweden" },
    SWITZERLAND: { value: "CH", text: "Switzerland" },
    SYRIA: { value: "SY", text: "Syria" },
    TAJIKISTAN: { value: "TJ", text: "Tajikistan" },
    TANZANIA: { value: "TZ", text: "Tanzania" },
    THAILAND: { value: "TH", text: "Thailand" },
    TOGO: { value: "TG", text: "Togo" },
    TONGA: { value: "TO", text: "Tonga" },
    TRINIDAD_TOBAGO: { value: "TT", text: "Trinidad and Tobago" },
    TUNISIA: { value: "TN", text: "Tunisia" },
    TURKEY: { value: "TR", text: "Turkey" },
    TURKMENISTAN: { value: "TM", text: "Turkmenistan" },
    TUVALU: { value: "TV", text: "Tuvalu" },
    UGANDA: { value: "UG", text: "Uganda" },
    UKRAINE: { value: "UA", text: "Ukraine" },
    UAE: { value: "AE", text: "United Arab Emirates" },
    US: { value: "US", text: "United States" },
    URUGUAY: { value: "UY", text: "Uruguay" },
    UZBEKISTAN: { value: "UZ", text: "Uzbekistan" },
    VANUATU: { value: "VU", text: "Vanuatu" },
    VENEZUELA: { value: "VE", text: "Venezuela" },
    VIETNAM: { value: "VN", text: "Vietnam" },
    YEMEN: { value: "YE", text: "Yemen" },
    ZAMBIA: { value: "ZM", text: "Zambia" },
    ZIMBABWE: { value: "ZW", text: "Zimbabwe" }
  }
}