name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Export Proxy URL
        run: echo "PROXYURL=f2f-cri-outbound-proxy-proxy.review-o.dev.account.gov.uk" >> $GITHUB_ENV
      - name: Run lint
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run test and write coverage
        run: yarn test:coverage
      - name: Run browser tests
        run: npm run test:browser:ci
        env:
          IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
