name: Pre-merge checks

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [main]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run test and write coverage
        run: yarn test:coverage
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
      - name: Run browser & e2e tests
        run: yarn run test:e2e:cd
        env: 
          IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
          CUSTOM_FE_URL: https://f2f-cri-front.review-o.dev.account.gov.uk
          LANGUAGE_TOGGLE_DISABLED: false
          PROXYURL: f2f-cri-outbound-proxy-proxy.review-o.dev.account.gov.uk
          F2F_FE_BASE_URL: https://f2f-cri-front.review-o.dev.account.gov.uk
          API_BASE_URL: https://api-f2f-cri-api.review-o.dev.account.gov.uk
          TEST_HARNESS_URL: https://f2f-test-harness-testharness.review-o.dev.account.gov.uk
          LETTER_LANGUAGE_CHOICE_ENABLED: true
          SESSION_TABLE: session-f2f-cri-ddb
      - name: Archive browser tests results
        uses: actions/upload-artifact@v6
        with:
          name: browser-tests-report
          path: test/reports/f2f-reports/

  sonar-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test:coverage
      - name: Run SonarCloud Scan
        if: success() && github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
