name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: "detect-secrets --all-files"

  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test:coverage
      - run: bash ./run-browser-tests.sh
      - name: Archive browser tests results
        uses: actions/upload-artifact@v4
        with:
          name: f2f-code-coverage-report
          path: test/reports/f2f-reports/

  sonar-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - name: "Run SonarCloud Scan"
        if: ${{ success() && github.actor != 'dependabot[bot]' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
